### ISSUE TITLE
能提供一个样例吗

### ISSUE THREAD

**Issue by weiweisss** [LingweiMeng/Whisper-Sidecar#1]
能提供一个样例来说明如何使用该模型，识别多说话人音频中指定说话人说的话吗？

**Comment by LingweiMeng** [comment]
Hi. I've update the README.md for clarity.

For target-talker ASR training and reference, please first organize your data according to what is mentioned in the README. 
Then use `python finetune.py --taget_asr True` to train your model, and finally use `python evaluation.py --taget_asr True` for reference.
