### ISSUE TITLE
pretrained model for inference

### ISSUE THREAD

**Issue by WolfverusWasTaken** [LingweiMeng/Whisper-Sidecar#2]
Hi, do you have a pretrained model that I can use for inference and further finetuning?

**Comment by LingweiMeng** [comment]
Hi. Unfortunately, I did not back-up a pre-trained model. 
By preparing the data and training according to the instructions, you can achieve results comparable to those in the paper.

**Comment by WolfverusWasTaken** [comment]
Appreciate your response from before. I do have another question regarding the training component.

![image](https://github.com/user-attachments/assets/f5965e2b-45f9-4695-9c58-bf8730961457)
can you check if this was a normal behavior that you have faced when training? 
The Orange line is when I trained with both Libri2Mix + Libri3Mix (mixed_clean only) 
The Green line is when I further finetuned with the previous weights from 50k steps, with Libri2Mix mixed_clean + Libri3Mix mixed_clean + my custom dataset similar to LibriSpeechMix and Libri3Mix.

Both these times, the loss seems to be plateauing for extensive periods of time. I have tried changing the learning rate but the case of the model plateauing is pretty constant.

Am I missing something out or is this the expected behaviour?

**Comment by LingweiMeng** [comment]
It is normal for the training model loss to plateau this way, but the curve with your custom data is high (I don't know if this is normal). 
Can the model work properly? You can first turn off the target talker ASR setting and train the model to see if it works when only performing multi-talker ASR with addtional custom data.

**Comment by WolfverusWasTaken** [comment]
> You can first turn off the target talker ASR setting and train the model to see if it works when only performing multi-talker ASR with addtional custom data.

It doesn't seem to be,
`{'loss': 3.3584, 'grad_norm': 9.98060131072998, 'learning_rate': 0.00019685156445556947, 'epoch': 1.32}                                                                               
{'loss': 3.3074, 'grad_norm': 279.125244140625, 'learning_rate': 0.0001968015018773467, 'epoch': 1.34}                                                                                
{'loss': 3.2829, 'grad_norm': 18.79864501953125, 'learning_rate': 0.0001967514392991239, 'epoch': 1.36}                                                                               
{'loss': 3.195, 'grad_norm': 7.681273460388184, 'learning_rate': 0.00019670137672090114, 'epoch': 1.37}                                                                               
{'loss': 3.1961, 'grad_norm': 20.449207305908203, 'learning_rate': 0.00019665131414267837, 'epoch': 1.39}                                                                             
{'loss': 3.2138, 'grad_norm': 9.717011451721191, 'learning_rate': 0.0001966017521902378, 'epoch': 1.41}                                                                               
{'loss': 3.2815, 'grad_norm': 47.17121887207031, 'learning_rate': 0.00019655168961201503, 'epoch': 1.43}                                                                              
{'loss': 3.2605, 'grad_norm': 14.2120943069458, 'learning_rate': 0.00019650162703379223, 'epoch': 1.45}                                                                               
{'loss': 3.2787, 'grad_norm': 19.884361267089844, 'learning_rate': 0.00019645156445556946, 'epoch': 1.47}                                                                             
{'loss': 3.2396, 'grad_norm': 12.961444854736328, 'learning_rate': 0.0001964015018773467, 'epoch': 1.49}  ` 

I only ran this for 5000 steps, But the loss is plateauing, do I run it for longer periods? changing the target talker ASR setting to false doesn't train the sidecar component right?

**Comment by LingweiMeng** [comment]
1. Yes, please train it for longer periods.
2. Changing the target talker ASR setting to False will train the sidecar component, but the target talker identifier (TTI) will not be trained.

**Comment by WolfverusWasTaken** [comment]
>   File "/workspace/Whisper-Sidecar/Whisper-Sidecar/model/modeling_whisper_sidecar.py", line 506, in decoder_soft_prompt_hook
    inputs_embeds[:, 1:self.soft_prompt_embeds.shape[0]+1] = self.soft_prompt_embeds
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: The expanded size of the tensor (3) must match the existing size (4) at non-singleton dimension 1.  Target sizes: [24, 3, 768].  Tensor sizes: [4, 768]

Have you faced an error similar to this? I have been getting this at the end of the 15th epoch. Is this a dataset issue?

I have read the paper and it says the soft prompt embedding gets updated during the training process?

**Comment by LingweiMeng** [comment]
I did not come across this error. I believe it is related to a dataset issue. Please debug with your custom data.

Yes, the soft prompt embedding gets updated during the training process.
